const genText = document.getElementById("gen-text")

genText.addEventListener("click", function() {
  let messages = [
    "you're doing your best, keep going, rafael!",
    "thank you for existing",
    "i'm so happy we met",
    "flowers grow back even after the harshest winters, you will too",
    "doing your best might look different each day, but at least you're trying",
    "you're good enough",
    "your existence matters",
    "you'll achieve your dreams one day",
    "i adore you",
    "please smile, happiness looks so gorgeous on you",
    "you're dealing with stuff the best you can, even if you don't feel like the best at it. i'm cheering you on!",
    "hope you know how loved you are",
    "YOU ARE SO AMAZING AND PRECIOUS !!!",
    "when you can't look on the bright side I will sit with you in the dark.",
    "you are doing amazingly, even if you dont feel like it, and I'm super proud of you.",
    "remember you are one in a million, you are loved, unique and unbelievably special just the way you are",
    "sorry if your naughty brain told you otherwise, but you are truly doing a great job.",
    "forgive yourself for not knowing better at the time.",
    "take a break, recharge, and come back stronger",
    "i don't always have the right words to help or make things better, but i care very much, i promise",
    "sending support and good wishes your way today. and cheering you on one step at a time - you're doing just fine",
    "when you feel like giving up, look back at how far you've come: be strong. stay on your path. never stop going.",
    "today is a beautiful day to remind you that you deserve everything you dream of and that you are capable of achieving everything you set your mind to.",
    "ONE DAY YOU WILL LOOK BACK ON THIS. AND YOU WILL BE PROUD THAT YOU DIDN'T GIVE UP. SO KEEP ON GOING. YOU GOT THIS!",
    "take care of that beautiful mind of yours! your mental health is just as important as your physical health. remember to give yourself some love today",
    "taking a break is not lazy",
    "slowing things down is not procrastination",
    "taking time to think is not indecisive",
    "all you need is love, so i give this",
    "taking care of yourself is not selfish",
    "taking time to heal is not a waste of time",
    "you are a strong person, you can overcome anything, you are a very beautiful person and you deserve things that are just as beautiful.",
    "i hope you smiled today. if not, quick, do it now!",
    "to me, you are perfect",
    "I AM PROUD OF YOU FOR SURVIVING ANOTHER DAY!!!",
    "wishing you a day free from whatever hell your brain says should be happening",
    "in case no one has told you, im so proud of you, and i know how hard you're trying",
    "i hope something nice comes your way, and you get the full bloom you deserve",
    "i'm cheering you on through it all, and hoping something nice blooms for you soon",
    "if you are reading this, i hope something good happens to you today.",
    "your hard work will pay off! every day you're getting stronger. everything you're doing matters, so please don't give up!",
    "if i get paid for being proud of you, i would be a millionaire by now, haha",
    "you can be happy, so don't give up on yourself like that. i see a lot of happiness in your future, please keep fighting for it. You CAN do it.",
    "you don't need to be the best. no one needs to eat the best apple every day. you just need a good one. and you're a good apple.",
    "may you be filled with lots of positive energy and yummy snacks.",
    "i really care about you and hope you're getting enough sleep and eating okay, and I'm always here for you!",
    "may this month be full of little joys, small victories, and tiny steps forward.",
    "don't be afraid to celebrate the mini successes! they do add up in the right direction!",
    "YOU JUST GOT: 1 order of happiness with a side of smiles and extra sunshine!",
    "i'm blessing your day! +I happiness +1 good luck positive thoughts.",
    "LIFE IS TOO SHORT, RAFAEL. SO DON'T SPEND IT TRAPPED SOMEWHERE YOU DON'T WANT TO BE!",
    "life can only be understood backwards: but it must be lived forward",
    "forgive yourself for past behaviors",
    "beauty begins the moment you decide to be yourself",
    "you might not feel like you are at your strongest right now and that's okay. just know that you have come this far and you are doing extremely well. you will come out on the other side as a much stronger person",
    "you are not behind it's not too late, you are exactly where you need to be right now. every step you've taken has been necessary give yourself credit, rather than berating yourself for how long your journey is taking. we all need our own time to travel our own distance",
    "you don't need to spend your time proving yourself to others. if someone doesn't appreciate you, it's not your job to convince them. you are enough and are doing AMAZING",
    "i am really blessed to know you in my life.",
    "you know, someone is happy today just because YOU exist.",
    "you're scared because you care, and caring is a never bad thing your feelings are real and valid",
    "the way you talk to yourself in your head matters. make sure that voice is kind",
    "your anxious thoughts are lying to you",
    "You are my greatest adventure.",
    "I wish I could tell you how much I love you, but there are no words for it.",
    "Your flaws are perfect for the heart thats meant to love you.",
    "I am in you and you in me, mutual in divine love.",
    "Come live in my heart and pay no rent.",
    "The world is so small compared to my love for you.",
    "I cant wait to see you again",
    "If I tell you I love you, can I keep you forever?",
    "I love you and I like you",
    "I miss you",
    "You wanna know who I'm in love with? Read the first word again.",
    "I absolutely adore you. Just FYI.",
    "Stop making me think about you! I'm busy",
    "Your texts make my day even better.",
    "Come to my dreams if you can. I'll kiss you there.",
    "You make me the happiest person on Earth.",
    "Every time you text me, I get butterflies.",
    "Such a stressful day. Want to blow off some steam tonight?",
    "I love you with all my heart.",
    "I cant wait to come home to you tonight",
    "Love = you + me.",
    "Forever and always, without a doubt, I am yours.",
    "I'm so lucky you're mine.",
    "Wanna know something? I love you.",
    "I only saw you for a second, but it made my day.",
    "Let it be known that I love you a lot. Wherever you go, I shall follow.",
    "I want to wake up every morning with the scent of your hair!",
    "In my eyes, you are perfect. I adore you.",
    "I want to go on a world tour with my queen someday.",
    "I cant imagine living a life without you. You are my reason to be.",
    "I love you more and more with each and every passing day.",
    "May I dance with you to the tune of a song that lasts forever?",
    "You have no idea the amount of happiness you brought into my life.",
    "I love you like I love my video games. You are really so special!",
    "I would like to fill my calendars with memories of you.",
    "MAHAL KITA",
    "You are like money. The more I get, the more I want!",
    "I might be the luckiest to find my soulmate in you!",
    "I hope to make you happy beyond belief.",
    "You tripped me, so I fell for you.",
    "Can you be the icing in my cupcake? HAHA",
    "I feel the sparks every time you kiss me.",
    "Can I borrow a kiss? I promise Ill give it back.",
    "I have discovered that home too has a smell. You are my home.",
    "To the sun and moon, I love you.",
    "The only thing I want to be an expert at is loving you!",
    "Every atom, molecule, and cell of me loves you.",
    "Im so lucky to have you! I love you forever!",
    "Being in love with you makes every morning worth getting up for.",
    "Its just you and me against the world. I love you!",
    "My love for you is like the water in the ocean. It will never dry up.",
    "I want to be your favorite hello, and hardest goodbye.",
    "To the moon and back, I love you.",
    "I have many reasons to die for, but only one to live for, that is you!",
    "You stole my heart and I dont want it back ever!",
    "Thank you, my love, for making me feel like the most beautiful person in the world.",
    "I am blessed to be with a man like you!",
    "I love you—now and always.",
    "Its you and me against the universe. Were the strongest team there is.",
    "Hold my hand, hold my heart, and hold me forever. I love you",
    "If I know what love is, it is because of you.",
    "You are my forever. I will love you always.",
    "I wish you were here, or I was there, or we were together anywhere",
    "Distance means so little when someone means so much",
    "You bring happiness into my life",
  ]
  const textEl = document.querySelector(".textMessage")
  textEl.textContent = messages[Math.floor( Math.random()*messages.length )]
})
